### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by RachelZheng** [suppechasper/optimaltransport#2]
Hello,

When I run IPCATransport with default parameters, there is an segmentation fault issue. The output is:

```
Scale: 0

capacityScaling: 1e+10
costScaling: 1e+10
Mass positive: 10000000000
Mass negative: -10000000000
Mass imbalance: 0
success: 1
objective: 0
primal.size(): 1
dual.size(): 2
stored 
cost: 0
nonzeros: 1
solution sumw: 1



Scale: 1

Neighborhood weight sum: 1
capacityScaling: 2e+10
costScaling: 1e+10
Mass positive: 20000000000
Mass negative: -20000000000
Mass imbalance: 0
success: 1
objective: 0
primal.size(): 4
dual.size(): 4
stored 
Neighborhood weight sum: 1
capacityScaling: 2e+10
costScaling: 1e+10
Mass positive: 20000000000
Mass negative: -20000000000
Mass imbalance: 0
success: 1
objective: 0
primal.size(): 4
dual.size(): 4
stored 
cost: 0
nonzeros: 2
solution sumw: 1

Segmentation fault: 11
```
And this is the dataset I tried to use:
[test_dataset.zip](https://github.com/suppechasper/optimaltransport/files/1746278/test_dataset.zip)

Could you tell me why I get this error? Thanks in advance!

**Comment by suppechasper** [comment]
Could you send me the data and exact commands you are using.

Thank you.

**Comment by suppechasper** [comment]
I see you are running the command line tools. They are not well tested, please use the R package until I can fix that.

**Comment by RachelZheng** [comment]
I am able to use the R package now. Thanks!
