### ISSUE TITLE
How to specify R_mop_install path

### ISSUE THREAD

**Issue by RachelZheng** [suppechasper/optimaltransport#3]
Hi, could you tell me how to customize the install path of this R package? I tried 

`cmake . -DCMAKE_INSTALL_PREFIX=/path/to/my/dest`

But it will still install to the default directory.

I also tried

`export CMAKE_INSTALL_PREFIX=/path/to/my/dest`

and it does not work either.

**Comment by suppechasper** [comment]
Instead of running make R_mop_install run make R_mop_build, this will create a mop_0.8.tar.gz file. You can install this package to R by running R CMD INSTALL mop_0.8.tar.gz  -l path to your R library tree

**Comment by RachelZheng** [comment]
That works. Thanks!
